package com.xlf.account.repository.mapper;

import com.xlf.account.entity.AccountFlowBakDo;
import com.xlf.account.entity.AccountFlowBakDoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface AccountFlowBakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    long countByExample(AccountFlowBakDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    int deleteByExample(AccountFlowBakDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    int deleteByPrimaryKey(Long flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    int insert(AccountFlowBakDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    int insertSelective(AccountFlowBakDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    List<AccountFlowBakDo> selectByExample(AccountFlowBakDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    AccountFlowBakDo selectByPrimaryKey(Long flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    int updateByExampleSelective(@Param("row") AccountFlowBakDo row, @Param("example") AccountFlowBakDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    int updateByExample(@Param("row") AccountFlowBakDo row, @Param("example") AccountFlowBakDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    int updateByPrimaryKeySelective(AccountFlowBakDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow_bak
     *
     * @mbg.generated 2022-07-20
     */
    int updateByPrimaryKey(AccountFlowBakDo row);
}