package com.xlf.account.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account_flow
 */
public class AccountFlowDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.flow_id
     *
     * @mbg.generated 2022-07-20
     */
    private Long flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.app_id
     *
     * @mbg.generated 2022-07-20
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.account_id
     *
     * @mbg.generated 2022-07-20
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.to_account_id
     *
     * @mbg.generated 2022-07-20
     */
    private Long toAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.user_id
     *
     * @mbg.generated 2022-07-20
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.to_user_id
     *
     * @mbg.generated 2022-07-20
     */
    private String toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.account_type
     *
     * @mbg.generated 2022-07-20
     */
    private Integer accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.to_account_type
     *
     * @mbg.generated 2022-07-20
     */
    private Integer toAccountType;

    /**
     * Database Column Remarks:
     *   transation id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.trans_id
     *
     * @mbg.generated 2022-07-20
     */
    private String transId;

    /**
     * Database Column Remarks:
     *   1-create account,2-recharge,3-withdraw,4-transaction,5-frozen,6-unfrozen
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.operate_type
     *
     * @mbg.generated 2022-07-20
     */
    private Integer operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.amount
     *
     * @mbg.generated 2022-07-20
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.currency_type
     *
     * @mbg.generated 2022-07-20
     */
    private String currencyType;

    /**
     * Database Column Remarks:
     *   balance after operation
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.balance
     *
     * @mbg.generated 2022-07-20
     */
    private Long balance;

    /**
     * Database Column Remarks:
     *   frozen_balance after operation
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.frozen_balance
     *
     * @mbg.generated 2022-07-20
     */
    private Long frozenBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.create_time
     *
     * @mbg.generated 2022-07-20
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.order_time
     *
     * @mbg.generated 2022-07-20
     */
    private Date orderTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.flow_id
     *
     * @return the value of account_flow.flow_id
     *
     * @mbg.generated 2022-07-20
     */
    public Long getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.flow_id
     *
     * @param flowId the value for account_flow.flow_id
     *
     * @mbg.generated 2022-07-20
     */
    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.app_id
     *
     * @return the value of account_flow.app_id
     *
     * @mbg.generated 2022-07-20
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.app_id
     *
     * @param appId the value for account_flow.app_id
     *
     * @mbg.generated 2022-07-20
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.account_id
     *
     * @return the value of account_flow.account_id
     *
     * @mbg.generated 2022-07-20
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.account_id
     *
     * @param accountId the value for account_flow.account_id
     *
     * @mbg.generated 2022-07-20
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.to_account_id
     *
     * @return the value of account_flow.to_account_id
     *
     * @mbg.generated 2022-07-20
     */
    public Long getToAccountId() {
        return toAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.to_account_id
     *
     * @param toAccountId the value for account_flow.to_account_id
     *
     * @mbg.generated 2022-07-20
     */
    public void setToAccountId(Long toAccountId) {
        this.toAccountId = toAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.user_id
     *
     * @return the value of account_flow.user_id
     *
     * @mbg.generated 2022-07-20
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.user_id
     *
     * @param userId the value for account_flow.user_id
     *
     * @mbg.generated 2022-07-20
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.to_user_id
     *
     * @return the value of account_flow.to_user_id
     *
     * @mbg.generated 2022-07-20
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.to_user_id
     *
     * @param toUserId the value for account_flow.to_user_id
     *
     * @mbg.generated 2022-07-20
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId == null ? null : toUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.account_type
     *
     * @return the value of account_flow.account_type
     *
     * @mbg.generated 2022-07-20
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.account_type
     *
     * @param accountType the value for account_flow.account_type
     *
     * @mbg.generated 2022-07-20
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.to_account_type
     *
     * @return the value of account_flow.to_account_type
     *
     * @mbg.generated 2022-07-20
     */
    public Integer getToAccountType() {
        return toAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.to_account_type
     *
     * @param toAccountType the value for account_flow.to_account_type
     *
     * @mbg.generated 2022-07-20
     */
    public void setToAccountType(Integer toAccountType) {
        this.toAccountType = toAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.trans_id
     *
     * @return the value of account_flow.trans_id
     *
     * @mbg.generated 2022-07-20
     */
    public String getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.trans_id
     *
     * @param transId the value for account_flow.trans_id
     *
     * @mbg.generated 2022-07-20
     */
    public void setTransId(String transId) {
        this.transId = transId == null ? null : transId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.operate_type
     *
     * @return the value of account_flow.operate_type
     *
     * @mbg.generated 2022-07-20
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.operate_type
     *
     * @param operateType the value for account_flow.operate_type
     *
     * @mbg.generated 2022-07-20
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.amount
     *
     * @return the value of account_flow.amount
     *
     * @mbg.generated 2022-07-20
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.amount
     *
     * @param amount the value for account_flow.amount
     *
     * @mbg.generated 2022-07-20
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.currency_type
     *
     * @return the value of account_flow.currency_type
     *
     * @mbg.generated 2022-07-20
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.currency_type
     *
     * @param currencyType the value for account_flow.currency_type
     *
     * @mbg.generated 2022-07-20
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType == null ? null : currencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.balance
     *
     * @return the value of account_flow.balance
     *
     * @mbg.generated 2022-07-20
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.balance
     *
     * @param balance the value for account_flow.balance
     *
     * @mbg.generated 2022-07-20
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.frozen_balance
     *
     * @return the value of account_flow.frozen_balance
     *
     * @mbg.generated 2022-07-20
     */
    public Long getFrozenBalance() {
        return frozenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.frozen_balance
     *
     * @param frozenBalance the value for account_flow.frozen_balance
     *
     * @mbg.generated 2022-07-20
     */
    public void setFrozenBalance(Long frozenBalance) {
        this.frozenBalance = frozenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.create_time
     *
     * @return the value of account_flow.create_time
     *
     * @mbg.generated 2022-07-20
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.create_time
     *
     * @param createTime the value for account_flow.create_time
     *
     * @mbg.generated 2022-07-20
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.order_time
     *
     * @return the value of account_flow.order_time
     *
     * @mbg.generated 2022-07-20
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.order_time
     *
     * @param orderTime the value for account_flow.order_time
     *
     * @mbg.generated 2022-07-20
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow
     *
     * @mbg.generated 2022-07-20
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AccountFlowDo other = (AccountFlowDo) that;
        return (this.getFlowId() == null ? other.getFlowId() == null : this.getFlowId().equals(other.getFlowId()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(other.getAccountId()))
            && (this.getToAccountId() == null ? other.getToAccountId() == null : this.getToAccountId().equals(other.getToAccountId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getToUserId() == null ? other.getToUserId() == null : this.getToUserId().equals(other.getToUserId()))
            && (this.getAccountType() == null ? other.getAccountType() == null : this.getAccountType().equals(other.getAccountType()))
            && (this.getToAccountType() == null ? other.getToAccountType() == null : this.getToAccountType().equals(other.getToAccountType()))
            && (this.getTransId() == null ? other.getTransId() == null : this.getTransId().equals(other.getTransId()))
            && (this.getOperateType() == null ? other.getOperateType() == null : this.getOperateType().equals(other.getOperateType()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getCurrencyType() == null ? other.getCurrencyType() == null : this.getCurrencyType().equals(other.getCurrencyType()))
            && (this.getBalance() == null ? other.getBalance() == null : this.getBalance().equals(other.getBalance()))
            && (this.getFrozenBalance() == null ? other.getFrozenBalance() == null : this.getFrozenBalance().equals(other.getFrozenBalance()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getOrderTime() == null ? other.getOrderTime() == null : this.getOrderTime().equals(other.getOrderTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow
     *
     * @mbg.generated 2022-07-20
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFlowId() == null) ? 0 : getFlowId().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        result = prime * result + ((getToAccountId() == null) ? 0 : getToAccountId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getToUserId() == null) ? 0 : getToUserId().hashCode());
        result = prime * result + ((getAccountType() == null) ? 0 : getAccountType().hashCode());
        result = prime * result + ((getToAccountType() == null) ? 0 : getToAccountType().hashCode());
        result = prime * result + ((getTransId() == null) ? 0 : getTransId().hashCode());
        result = prime * result + ((getOperateType() == null) ? 0 : getOperateType().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getCurrencyType() == null) ? 0 : getCurrencyType().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        result = prime * result + ((getFrozenBalance() == null) ? 0 : getFrozenBalance().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getOrderTime() == null) ? 0 : getOrderTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow
     *
     * @mbg.generated 2022-07-20
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", flowId=").append(flowId);
        sb.append(", appId=").append(appId);
        sb.append(", accountId=").append(accountId);
        sb.append(", toAccountId=").append(toAccountId);
        sb.append(", userId=").append(userId);
        sb.append(", toUserId=").append(toUserId);
        sb.append(", accountType=").append(accountType);
        sb.append(", toAccountType=").append(toAccountType);
        sb.append(", transId=").append(transId);
        sb.append(", operateType=").append(operateType);
        sb.append(", amount=").append(amount);
        sb.append(", currencyType=").append(currencyType);
        sb.append(", balance=").append(balance);
        sb.append(", frozenBalance=").append(frozenBalance);
        sb.append(", createTime=").append(createTime);
        sb.append(", orderTime=").append(orderTime);
        sb.append("]");
        return sb.toString();
    }
}