package com.xlf.trade.repository.mapper;

import com.xlf.trade.entity.PayOrderDo;
import com.xlf.trade.entity.PayOrderDoExample;
import com.xlf.trade.entity.PayOrderDoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    long countByExample(PayOrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int deleteByExample(PayOrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int insert(PayOrderDoWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int insertSelective(PayOrderDoWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    List<PayOrderDoWithBLOBs> selectByExampleWithBLOBs(PayOrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    List<PayOrderDo> selectByExample(PayOrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    PayOrderDoWithBLOBs selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int updateByExampleSelective(@Param("row") PayOrderDoWithBLOBs row, @Param("example") PayOrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int updateByExampleWithBLOBs(@Param("row") PayOrderDoWithBLOBs row, @Param("example") PayOrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int updateByExample(@Param("row") PayOrderDo row, @Param("example") PayOrderDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int updateByPrimaryKeySelective(PayOrderDoWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int updateByPrimaryKeyWithBLOBs(PayOrderDoWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbg.generated 2022-07-17
     */
    int updateByPrimaryKey(PayOrderDo row);
}