package com.xlf.trade.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account_info
 */
public class AccountInfoDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.id
     *
     * @mbg.generated 2022-07-17
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.user_id
     *
     * @mbg.generated 2022-07-17
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.user_name
     *
     * @mbg.generated 2022-07-17
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_name
     *
     * @mbg.generated 2022-07-17
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_type
     *
     * @mbg.generated 2022-07-17
     */
    private Integer accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.balance
     *
     * @mbg.generated 2022-07-17
     */
    private Long balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.frozen_balance
     *
     * @mbg.generated 2022-07-17
     */
    private Long frozenBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.currency_type
     *
     * @mbg.generated 2022-07-17
     */
    private String currencyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.status
     *
     * @mbg.generated 2022-07-17
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.create_type
     *
     * @mbg.generated 2022-07-17
     */
    private Integer createType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.create_by
     *
     * @mbg.generated 2022-07-17
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.create_time
     *
     * @mbg.generated 2022-07-17
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.update_time
     *
     * @mbg.generated 2022-07-17
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.id
     *
     * @return the value of account_info.id
     *
     * @mbg.generated 2022-07-17
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.id
     *
     * @param id the value for account_info.id
     *
     * @mbg.generated 2022-07-17
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.user_id
     *
     * @return the value of account_info.user_id
     *
     * @mbg.generated 2022-07-17
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.user_id
     *
     * @param userId the value for account_info.user_id
     *
     * @mbg.generated 2022-07-17
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.user_name
     *
     * @return the value of account_info.user_name
     *
     * @mbg.generated 2022-07-17
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.user_name
     *
     * @param userName the value for account_info.user_name
     *
     * @mbg.generated 2022-07-17
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_name
     *
     * @return the value of account_info.account_name
     *
     * @mbg.generated 2022-07-17
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_name
     *
     * @param accountName the value for account_info.account_name
     *
     * @mbg.generated 2022-07-17
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_type
     *
     * @return the value of account_info.account_type
     *
     * @mbg.generated 2022-07-17
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_type
     *
     * @param accountType the value for account_info.account_type
     *
     * @mbg.generated 2022-07-17
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.balance
     *
     * @return the value of account_info.balance
     *
     * @mbg.generated 2022-07-17
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.balance
     *
     * @param balance the value for account_info.balance
     *
     * @mbg.generated 2022-07-17
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.frozen_balance
     *
     * @return the value of account_info.frozen_balance
     *
     * @mbg.generated 2022-07-17
     */
    public Long getFrozenBalance() {
        return frozenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.frozen_balance
     *
     * @param frozenBalance the value for account_info.frozen_balance
     *
     * @mbg.generated 2022-07-17
     */
    public void setFrozenBalance(Long frozenBalance) {
        this.frozenBalance = frozenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.currency_type
     *
     * @return the value of account_info.currency_type
     *
     * @mbg.generated 2022-07-17
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.currency_type
     *
     * @param currencyType the value for account_info.currency_type
     *
     * @mbg.generated 2022-07-17
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType == null ? null : currencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.status
     *
     * @return the value of account_info.status
     *
     * @mbg.generated 2022-07-17
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.status
     *
     * @param status the value for account_info.status
     *
     * @mbg.generated 2022-07-17
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.create_type
     *
     * @return the value of account_info.create_type
     *
     * @mbg.generated 2022-07-17
     */
    public Integer getCreateType() {
        return createType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.create_type
     *
     * @param createType the value for account_info.create_type
     *
     * @mbg.generated 2022-07-17
     */
    public void setCreateType(Integer createType) {
        this.createType = createType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.create_by
     *
     * @return the value of account_info.create_by
     *
     * @mbg.generated 2022-07-17
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.create_by
     *
     * @param createBy the value for account_info.create_by
     *
     * @mbg.generated 2022-07-17
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.create_time
     *
     * @return the value of account_info.create_time
     *
     * @mbg.generated 2022-07-17
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.create_time
     *
     * @param createTime the value for account_info.create_time
     *
     * @mbg.generated 2022-07-17
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.update_time
     *
     * @return the value of account_info.update_time
     *
     * @mbg.generated 2022-07-17
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.update_time
     *
     * @param updateTime the value for account_info.update_time
     *
     * @mbg.generated 2022-07-17
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated 2022-07-17
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AccountInfoDo other = (AccountInfoDo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getAccountName() == null ? other.getAccountName() == null : this.getAccountName().equals(other.getAccountName()))
            && (this.getAccountType() == null ? other.getAccountType() == null : this.getAccountType().equals(other.getAccountType()))
            && (this.getBalance() == null ? other.getBalance() == null : this.getBalance().equals(other.getBalance()))
            && (this.getFrozenBalance() == null ? other.getFrozenBalance() == null : this.getFrozenBalance().equals(other.getFrozenBalance()))
            && (this.getCurrencyType() == null ? other.getCurrencyType() == null : this.getCurrencyType().equals(other.getCurrencyType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateType() == null ? other.getCreateType() == null : this.getCreateType().equals(other.getCreateType()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated 2022-07-17
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getAccountName() == null) ? 0 : getAccountName().hashCode());
        result = prime * result + ((getAccountType() == null) ? 0 : getAccountType().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        result = prime * result + ((getFrozenBalance() == null) ? 0 : getFrozenBalance().hashCode());
        result = prime * result + ((getCurrencyType() == null) ? 0 : getCurrencyType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateType() == null) ? 0 : getCreateType().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated 2022-07-17
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", accountName=").append(accountName);
        sb.append(", accountType=").append(accountType);
        sb.append(", balance=").append(balance);
        sb.append(", frozenBalance=").append(frozenBalance);
        sb.append(", currencyType=").append(currencyType);
        sb.append(", status=").append(status);
        sb.append(", createType=").append(createType);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}